### ISSUE TITLE
rviz not functional

### ISSUE THREAD

**Issue by pv33** [ivaROS/pyrobot_minimal#2]
## Steps to reproduce

  1. Launch robot in Gazebo and instantiate controller.
  2. Launch robot visualization.

## Observed Results

*  Note transform errors in rviz model.

## Expected Results

  * Model in rviz should mirror actual robot model in Gazebo.

## Relevant Code

What is the source of this problem in the rviz settings?  Might Shiyu be able to help us?  Or Justin?

Shiyu, Justin, what could be the source of missing transforms in a robot model when rviz-ing?  Might it be that the Gazebo URDF does not actually include them?

**Comment by mass2010chromium** [comment]
Fix: `rosrun robot_state_publisher robot_state_publisher`

**Comment by drjsmith** [comment]
@pv33 the URDF specifies the links and joints. The robot_state_publisher uses that information, along with the current state of the joints, to perform the kinematics computations and publish the respective transforms.
The `robot_state_publisher` node should be included in the robot launch file.
